# Generated by Django 4.1.5 on 2023-01-16 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fittnessAppEcommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='diet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fittnessAppEcommerce.diet'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='training',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fittnessAppEcommerce.trainingmode'),
        ),
    ]
